#!/bin/bash

set -o errexit

set -o nounset


worker_ready(){
    celery -A real_estate inspect ping
}

until worker_ready; do 
    >&2 echo "🔜🔜🔜 .... Celery Workers Not Available Yet .... 🔜🔜🔜"
    sleep 1

done
>&2 echo '✔️✔️✔️ ... Celery Workers Are Available And Ready ... ✔️✔️✔️'

flower \
    --app=real_estate \
    --broker="${CELERY_BROKER}"